name: Build Windows Executable

on: [push]

jobs:
  pyinstaller-build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create Executable
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.11'
          spec: 'nanoMIDIPlayer.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'nanoMIDIPlayer'
          options: --onefile, --icon="./assets/icon.png", --hidden-import=mido.backends.rtmidi, --noconsole

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: nanoMIDIPlayer
          path: ./dist/nanoMIDIPlayer.exe
